# Generated by Django 5.2.4 on 2025-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#FFFFFF', max_length=20),
            preserve_default=False,
        ),
    ]
